#!/bin/bash

FILE="CoppeliaSim_Edu_V4_0_0_Ubuntu18_04.tar.xz"
URL="https://www.coppeliarobotics.com/files/$FILE"

if [ ! -f "/tmp/$FILE" ]; then
	wget -q --show-progress $URL -O "/tmp/$FILE"
fi

tar -xf "/tmp/$FILE" -C /tmp/
mv /tmp/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04 /opt/coppelia-sim-edu
